# Data Construction – Turkish Macroeconomic Dataset

This notebook builds the macroeconomic dataset used in the analysis.

Steps:
1. Download macroeconomic data from EVDS
2. Clean and standardize the series
3. Align monthly observations
4. Construct the final dataset

In [1]:
import pandas as pd
import numpy as np

print("environment ready")

environment ready

In [2]:
from pathlib import Path

project_path = Path("..")

raw_path = project_path / "data" / "raw"
processed_path = project_path / "data" / "processed"

print(raw_path)
print(processed_path)

..\data\raw
..\data\processed

In [3]:
# load processed datasets again

tge = pd.read_csv(processed_path / "tge_2019_2025.csv")
usd = pd.read_csv(processed_path / "usdtry_2019_2025.csv")
cpi = pd.read_csv(processed_path / "cpi_2019_2025.csv")
ipi = pd.read_csv(processed_path / "ipi_2019_2025.csv")
unemp = pd.read_csv(processed_path / "unemployment_2019_2025.csv")
bist = pd.read_csv(processed_path / "bist_2019_2025.csv")

In [4]:
tge["date"] = pd.to_datetime(tge["date"])
usd["date"] = pd.to_datetime(usd["date"])
cpi["date"] = pd.to_datetime(cpi["date"])
ipi["date"] = pd.to_datetime(ipi["date"])
unemp["date"] = pd.to_datetime(unemp["date"])
bist["date"] = pd.to_datetime(bist["date"])

In [5]:
macro_ext = tge

macro_ext = pd.merge(macro_ext, usd, on="date", how="inner")
macro_ext = pd.merge(macro_ext, cpi, on="date", how="inner")
macro_ext = pd.merge(macro_ext, ipi, on="date", how="inner")
macro_ext = pd.merge(macro_ext, unemp, on="date", how="inner")
macro_ext = pd.merge(macro_ext, bist, on="date", how="inner")

In [6]:
macro_ext.head()

        date        tge    usdtry     cpi        ipi  unemployment     bist
0 2019-01-01  80.113304  5.369391  398.07  80.704455          13.6  1040.74
1 2019-02-01  78.790390  5.262055  398.71  81.633131          13.8  1045.30
2 2019-03-01  81.100494  5.441938  402.81  84.080546          13.9   937.84
3 2019-04-01  83.611706  5.735771  409.63  83.611290          13.8   954.16
4 2019-05-01  77.045675  6.049445  413.52  84.307872          13.7   905.90

In [7]:
tge.head()

        date        tge
0 2019-01-01  80.113304
1 2019-02-01  78.790390
2 2019-03-01  81.100494
3 2019-04-01  83.611706
4 2019-05-01  77.045675

In [8]:
tge.columns

Index(['date', 'tge'], dtype='str')

In [9]:
print(tge.columns)

Index(['date', 'tge'], dtype='str')

In [10]:
print(tge.columns)

Index(['date', 'tge'], dtype='str')

In [11]:
usd_new = pd.read_excel("../data/raw/EVDS_usdtry_2019_2025.xlsx")

usd_new.head()

c:\Users\LenovoTuncay\Documents\turkey_macro_var_project\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

     Tarih TP_DK_USD_A_YTL Unnamed: 2
0  2019-01        5.369391        NaN
1  2019-02        5.262055        NaN
2  2019-03        5.441938        NaN
3  2019-04        5.735771        NaN
4  2019-05        6.049445        NaN

In [12]:
usd_new = usd_new[["Tarih", "TP_DK_USD_A_YTL"]]

usd_new = usd_new.rename(columns={
    "Tarih": "date",
    "TP_DK_USD_A_YTL": "usdtry"
})

In [13]:
usd_new.head()

      date    usdtry
0  2019-01  5.369391
1  2019-02  5.262055
2  2019-03  5.441938
3  2019-04  5.735771
4  2019-05  6.049445

In [14]:
usd_new.tail(10)

                 date                                   usdtry
82            2025-11                                 42.17916
83            2025-12                                42.586096
84                NaN                                      NaN
85                NaN                                      NaN
86  Seri Açıklamaları                                      NaN
87    TP.DK.USD.A.YTL  (USD)  ABD  Doları  (Döviz  Alış)-Düzey
88                NaN                                      NaN
89             Notlar                                      NaN
90    TP.DK.USD.A.YTL                             Veri Kaynağı
91                NaN                                Etiketler

In [15]:
usd_new = usd_new.dropna()

In [16]:
usd_new.tail()

               date                                   usdtry
81          2025-10                                 41.73025
82          2025-11                                 42.17916
83          2025-12                                42.586096
87  TP.DK.USD.A.YTL  (USD)  ABD  Doları  (Döviz  Alış)-Düzey
90  TP.DK.USD.A.YTL                             Veri Kaynağı

In [17]:
usd_new = usd_new[~usd_new["date"].str.contains("TP", na=False)]

In [18]:
usd_new.tail()

       date     usdtry
79  2025-08   40.72831
80  2025-09  41.219214
81  2025-10   41.73025
82  2025-11   42.17916
83  2025-12  42.586096

In [19]:
usd_new["date"] = pd.to_datetime(usd_new["date"])

In [20]:
usd_new["usdtry"] = pd.to_numeric(usd_new["usdtry"])

In [21]:
usd_new.info()

<class 'pandas.DataFrame'>
Index: 84 entries, 0 to 83
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    84 non-null     datetime64[us]
 1   usdtry  84 non-null     float64
dtypes: datetime64[us](1), float64(1)
memory usage: 2.0 KB

In [22]:
usd_new.to_csv("../data/processed/usdtry_2019_2025.csv", index=False)

In [23]:
tge = pd.read_csv("../data/processed/tge_2019_2025.csv")
usd = pd.read_csv("../data/processed/usdtry_2019_2025.csv")

tge["date"] = pd.to_datetime(tge["date"])
usd["date"] = pd.to_datetime(usd["date"])

In [24]:
macro_ext = pd.merge(tge, usd, on="date", how="inner")

macro_ext.head()

        date        tge    usdtry
0 2019-01-01  80.113304  5.369391
1 2019-02-01  78.790390  5.262055
2 2019-03-01  81.100494  5.441938
3 2019-04-01  83.611706  5.735771
4 2019-05-01  77.045675  6.049445

In [25]:
macro_ext.info()

<class 'pandas.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    84 non-null     datetime64[us]
 1   tge     84 non-null     float64
 2   usdtry  84 non-null     float64
dtypes: datetime64[us](1), float64(2)
memory usage: 2.1 KB

In [26]:
macro_ext = pd.merge(tge, usd, on="date", how="inner")
macro_ext.head()

        date        tge    usdtry
0 2019-01-01  80.113304  5.369391
1 2019-02-01  78.790390  5.262055
2 2019-03-01  81.100494  5.441938
3 2019-04-01  83.611706  5.735771
4 2019-05-01  77.045675  6.049445

In [27]:
macro_ext.to_csv("../data/processed/macro_extension_2019_2025.csv", index=False)

In [28]:
cpi_new = pd.read_excel("../data/raw/EVDS_cpi_2019_2025.xlsx")

cpi_new.head()

c:\Users\LenovoTuncay\Documents\turkey_macro_var_project\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

     Tarih TP_GENENDEKS_T1 Unnamed: 2
0  2019-01          398.07        NaN
1  2019-02          398.71        NaN
2  2019-03          402.81        NaN
3  2019-04          409.63        NaN
4  2019-05          413.52        NaN

In [29]:
cpi_new = cpi_new[["Tarih", "TP_GENENDEKS_T1"]]

cpi_new = cpi_new.rename(columns={
    "Tarih": "date",
    "TP_GENENDEKS_T1": "cpi"
})

In [30]:
cpi_new.head()

      date     cpi
0  2019-01  398.07
1  2019-02  398.71
2  2019-03  402.81
3  2019-04  409.63
4  2019-05  413.52

In [31]:
cpi_new.tail(10)

                 date                            cpi
86  Seri Açıklamaları                            NaN
87    TP.GENENDEKS.T1  Genel Endeks (2003=100)-Düzey
88                NaN                            NaN
89             Notlar                            NaN
90    TP.GENENDEKS.T1                   Veri Kaynağı
91                NaN         Veri Yayımlama Takvimi
92                NaN      Uygulama Değişiklik Linki
93                NaN               Metodoloji Linki
94                NaN        Revizyon Politika Linki
95                NaN                      Etiketler

In [32]:
cpi_new = cpi_new[~cpi_new["date"].str.contains("TP", na=False)]

In [33]:
cpi_new = cpi_new.dropna()

In [34]:
cpi_new.tail()

       date      cpi
79  2025-08  3261.72
80  2025-09  3367.22
81  2025-10  3453.09
82  2025-11  3482.96
83  2025-12  3513.87

In [35]:
cpi_new["date"] = pd.to_datetime(cpi_new["date"])

In [36]:
cpi_new["cpi"] = pd.to_numeric(cpi_new["cpi"])

In [37]:
cpi_new.info()

<class 'pandas.DataFrame'>
Index: 84 entries, 0 to 83
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    84 non-null     datetime64[us]
 1   cpi     84 non-null     float64
dtypes: datetime64[us](1), float64(1)
memory usage: 2.0 KB

In [38]:
cpi_new.to_csv("../data/processed/cpi_2019_2025.csv", index=False)

In [39]:
cpi = pd.read_csv("../data/processed/cpi_2019_2025.csv")
cpi["date"] = pd.to_datetime(cpi["date"])

macro_ext = pd.merge(macro_ext, cpi, on="date", how="inner")

macro_ext.head()

        date        tge    usdtry     cpi
0 2019-01-01  80.113304  5.369391  398.07
1 2019-02-01  78.790390  5.262055  398.71
2 2019-03-01  81.100494  5.441938  402.81
3 2019-04-01  83.611706  5.735771  409.63
4 2019-05-01  77.045675  6.049445  413.52

In [40]:
macro_ext.to_csv("../data/processed/macro_extension_2019_2025.csv", index=False)

In [41]:
ipi_new = pd.read_excel("../data/raw/EVDS_ipi_2019_2025.xlsx")

ipi_new.head()

c:\Users\LenovoTuncay\Documents\turkey_macro_var_project\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

     Tarih TP_TSANAYMT2021_Y1 Unnamed: 2
0  2019-01          80.704455        NaN
1  2019-02          81.633131        NaN
2  2019-03          84.080546        NaN
3  2019-04           83.61129        NaN
4  2019-05          84.307872        NaN

In [43]:
ipi_new = ipi_new.iloc[:, :2]

ipi_new.columns = ["date", "ipi"]

In [44]:
ipi_new.columns

Index(['date', 'ipi'], dtype='str')

In [45]:
ipi_new = ipi_new.iloc[:, :2]

ipi_new.columns = ["date", "ipi"]

In [46]:
ipi_new.head()

      date        ipi
0  2019-01  80.704455
1  2019-02  81.633131
2  2019-03  84.080546
3  2019-04   83.61129
4  2019-05  84.307872

In [47]:
ipi_new.tail(10)

                  date                        ipi
85                 NaN                        NaN
86   Seri Açıklamaları                        NaN
87  TP.TSANAYMT2021.Y1        Toplam sanayi-Düzey
88                 NaN                        NaN
89              Notlar                        NaN
90  TP.TSANAYMT2021.Y1               Veri Kaynağı
91                 NaN  Uygulama Değişiklik Linki
92                 NaN           Metodoloji Linki
93                 NaN    Revizyon Politika Linki
94                 NaN                  Etiketler

In [48]:
ipi_new = ipi_new[~ipi_new["date"].str.contains("TP", na=False)]

In [49]:
ipi_new = ipi_new.dropna()

In [50]:
ipi_new.tail()

       date         ipi
79  2025-08  110.230261
80  2025-09  108.112518
81  2025-10  107.149674
82  2025-11   109.87524
83  2025-12  111.225559

In [51]:
ipi_new["date"] = pd.to_datetime(ipi_new["date"])

In [52]:
ipi_new["ipi"] = pd.to_numeric(ipi_new["ipi"])

In [53]:
ipi_new.info()

<class 'pandas.DataFrame'>
Index: 84 entries, 0 to 83
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    84 non-null     datetime64[us]
 1   ipi     84 non-null     float64
dtypes: datetime64[us](1), float64(1)
memory usage: 2.0 KB

In [54]:
ipi_new.to_csv("../data/processed/ipi_2019_2025.csv", index=False)

In [55]:
ipi = pd.read_csv("../data/processed/ipi_2019_2025.csv")
ipi["date"] = pd.to_datetime(ipi["date"])

macro_ext = pd.merge(macro_ext, ipi, on="date", how="inner")

macro_ext.head()

        date        tge    usdtry     cpi        ipi
0 2019-01-01  80.113304  5.369391  398.07  80.704455
1 2019-02-01  78.790390  5.262055  398.71  81.633131
2 2019-03-01  81.100494  5.441938  402.81  84.080546
3 2019-04-01  83.611706  5.735771  409.63  83.611290
4 2019-05-01  77.045675  6.049445  413.52  84.307872

In [56]:
macro_ext.to_csv("../data/processed/macro_extension_2019_2025.csv", index=False)

In [57]:
unemp_new = pd.read_excel("../data/raw/EVDS_unemployment_2019_2025.xlsx")

unemp_new.head()

c:\Users\LenovoTuncay\Documents\turkey_macro_var_project\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

     Tarih TP_TIG08 Unnamed: 2
0  2019-01     13.6        NaN
1  2019-02     13.8        NaN
2  2019-03     13.9        NaN
3  2019-04     13.8        NaN
4  2019-05     13.7        NaN

In [58]:
unemp_new = unemp_new[["Tarih", "TP_TIG08"]]

unemp_new = unemp_new.rename(columns={
    "Tarih": "date",
    "TP_TIG08": "unemployment"
})

In [59]:
unemp_new.head()

      date unemployment
0  2019-01         13.6
1  2019-02         13.8
2  2019-03         13.9
3  2019-04         13.8
4  2019-05         13.7

In [60]:
unemp_new.tail(10)

                 date                unemployment
85                NaN                         NaN
86  Seri Açıklamaları                         NaN
87           TP.TIG08  8.İşsizlik oranı (%)-Düzey
88                NaN                         NaN
89             Notlar                         NaN
90           TP.TIG08                Veri Kaynağı
91                NaN   Uygulama Değişiklik Linki
92                NaN            Metodoloji Linki
93                NaN     Revizyon Politika Linki
94                NaN                   Etiketler

In [61]:
unemp_new = unemp_new[~unemp_new["date"].str.contains("TP", na=False)]

In [62]:
unemp_new = unemp_new.dropna()

In [63]:
unemp_new.tail()

       date unemployment
79  2025-08          8.5
80  2025-09          8.5
81  2025-10          8.4
82  2025-11          8.5
83  2025-12          7.7

In [64]:
unemp_new["date"] = pd.to_datetime(unemp_new["date"])

In [65]:
unemp_new["unemployment"] = pd.to_numeric(unemp_new["unemployment"])

In [66]:
unemp_new.info()

<class 'pandas.DataFrame'>
Index: 84 entries, 0 to 83
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          84 non-null     datetime64[us]
 1   unemployment  84 non-null     float64
dtypes: datetime64[us](1), float64(1)
memory usage: 2.0 KB

In [67]:
unemp_new.to_csv("../data/processed/unemployment_2019_2025.csv", index=False)

In [68]:
unemp = pd.read_csv("../data/processed/unemployment_2019_2025.csv")
unemp["date"] = pd.to_datetime(unemp["date"])

macro_ext = pd.merge(macro_ext, unemp, on="date", how="inner")

macro_ext.head()

        date        tge    usdtry     cpi        ipi  unemployment
0 2019-01-01  80.113304  5.369391  398.07  80.704455          13.6
1 2019-02-01  78.790390  5.262055  398.71  81.633131          13.8
2 2019-03-01  81.100494  5.441938  402.81  84.080546          13.9
3 2019-04-01  83.611706  5.735771  409.63  83.611290          13.8
4 2019-05-01  77.045675  6.049445  413.52  84.307872          13.7

In [69]:
macro_ext.to_csv("../data/processed/macro_extension_2019_2025.csv", index=False)

In [70]:
bist_new = pd.read_excel("../data/raw/EVDS_bist_2019_2025.xlsx")

bist_new.head()

c:\Users\LenovoTuncay\Documents\turkey_macro_var_project\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

     Tarih TP_MK_F_BILESIK Unnamed: 2
0  2019-01         1040.74        NaN
1  2019-02          1045.3        NaN
2  2019-03          937.84        NaN
3  2019-04          954.16        NaN
4  2019-05           905.9        NaN

In [71]:
bist_new = bist_new.iloc[:, :2]

bist_new.columns = ["date", "bist"]

bist_new.head()

      date     bist
0  2019-01  1040.74
1  2019-02   1045.3
2  2019-03   937.84
3  2019-04   954.16
4  2019-05    905.9

In [72]:
bist_new = bist_new[~bist_new["date"].astype(str).str.contains("TP", na=False)]

bist_new = bist_new.dropna()

In [73]:
bist_new["date"] = pd.to_datetime(bist_new["date"])

bist_new["bist"] = pd.to_numeric(bist_new["bist"])

In [74]:
bist_new.info()

<class 'pandas.DataFrame'>
Index: 84 entries, 0 to 83
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    84 non-null     datetime64[us]
 1   bist    84 non-null     float64
dtypes: datetime64[us](1), float64(1)
memory usage: 2.0 KB

In [75]:
bist_new.to_csv("../data/processed/bist_2019_2025.csv", index=False)

In [76]:
bist = pd.read_csv("../data/processed/bist_2019_2025.csv")

bist["date"] = pd.to_datetime(bist["date"])

macro_ext = pd.merge(macro_ext, bist, on="date", how="inner")

macro_ext.head()

        date        tge    usdtry     cpi        ipi  unemployment     bist
0 2019-01-01  80.113304  5.369391  398.07  80.704455          13.6  1040.74
1 2019-02-01  78.790390  5.262055  398.71  81.633131          13.8  1045.30
2 2019-03-01  81.100494  5.441938  402.81  84.080546          13.9   937.84
3 2019-04-01  83.611706  5.735771  409.63  83.611290          13.8   954.16
4 2019-05-01  77.045675  6.049445  413.52  84.307872          13.7   905.90

In [77]:
macro_ext.to_csv("../data/processed/macro_extension_2019_2025.csv", index=False)

In [78]:
macro_ext.info()

<class 'pandas.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          84 non-null     datetime64[us]
 1   tge           84 non-null     float64
 2   usdtry        84 non-null     float64
 3   cpi           84 non-null     float64
 4   ipi           84 non-null     float64
 5   unemployment  84 non-null     float64
 6   bist          84 non-null     float64
dtypes: datetime64[us](1), float64(6)
memory usage: 4.7 KB

In [79]:
macro_ext.isna().sum()

date            0
tge             0
usdtry          0
cpi             0
ipi             0
unemployment    0
bist            0
dtype: int64

In [80]:
macro_ext.shape

(84, 7)

In [81]:
tlref_new = pd.read_excel("../data/raw/EVDS_tlref_2019_2025.xlsx")

tlref_new.head()

c:\Users\LenovoTuncay\Documents\turkey_macro_var_project\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

     Tarih TP_BISTTLREF_ORAN Unnamed: 2
0  2019-01          23.57575        NaN
1  2019-02          23.91617        NaN
2  2019-03         23.583752        NaN
3  2019-04         24.702329        NaN
4  2019-05         25.138586        NaN

In [93]:
# ilk iki sütunu al
tlref_new = tlref_new.iloc[:, :2]

# isimleri düzelt
tlref_new.columns = ["date", "tlref"]

# datetime parse et (hatalı olanları NaT yap)
tlref_new["date"] = pd.to_datetime(tlref_new["date"], errors="coerce")

# metadata satırlarını temizle
tlref_new = tlref_new.dropna(subset=["date"])

# kontrol
tlref_new.tail()

         date      tlref
79 2025-08-01  42.708365
80 2025-09-01  41.240609
81 2025-10-01   39.98985
82 2025-11-01   39.30404
83 2025-12-01  38.404813

In [95]:
tlref_new.to_csv("../data/processed/tlref_2019_2025.csv", index=False)

In [96]:
tlref = pd.read_csv("../data/processed/tlref_2019_2025.csv")
tlref["date"] = pd.to_datetime(tlref["date"])

macro_ext = pd.merge(macro_ext, tlref, on="date", how="inner")

In [97]:
macro_ext.info()
macro_ext.isna().sum()
macro_ext.shape

<class 'pandas.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          84 non-null     datetime64[us]
 1   tge           84 non-null     float64
 2   usdtry        84 non-null     float64
 3   cpi           84 non-null     float64
 4   ipi           84 non-null     float64
 5   unemployment  84 non-null     float64
 6   bist          84 non-null     float64
 7   tlref         84 non-null     float64
dtypes: datetime64[us](1), float64(7)
memory usage: 5.4 KB

(84, 8)

## Output Dataset

The cleaned and merged dataset is saved as:

In [98]:
macro_ext.to_csv("../data/processed/macro_dataset_final_2019_2025.csv", index=False)


This dataset will be used in the econometric analysis notebooks.